### ISSUE TITLE
Start the cluster with nodes offline

### ISSUE THREAD

**Issue by mtfranchetto** [uber-node/ringpop-node#325]
Hi, first of all, thanks for the awesome work behind ringpop.
Just one question: we are experimenting with the framework and noticed that the bootstrap won't trigger its callback if one of the nodes is down (currently we are using 3 nodes). Is this by design or it's an unexpected behaviour? Because if the the nodes come up the cluster starts correctly, but in our infrastructure not all the nodes spawn at the same time (some nodes can take even 5 minutes to boot up), so the cluster could hang a lot.

Thanks
Mattia

**Comment by Raynos** [comment]
@mtfranchetto 

Ringpop is hard coded to only succeed bootstrap if at least 3 nodes are up.

Ringpop will work better if you deploy 10+ workers. Even if you do not have the hardware for multiple workers you can just spawn more nodejs workers then number of CPU cores to work around this.

**Comment by mtfranchetto** [comment]
Thank you very much, much clearer.
